# å¿…è¯»ï¼ï¼ï¼
# æ³¨æ„è§„åˆ™åœ¨æ»¡è¶³è‡ªå·±éœ€æ±‚æƒ…å†µä¸‹ï¼Œå°½é‡åšåˆ°ç²¾ç®€ï¼Œä¸è¦è¿‡åº¦å¤æ‚ï¼Œä»¥å…å½±å“æ€§èƒ½ã€‚
# è·‘è£¸æ ¸ç”¨æˆ·è¯·è‡ªè¡Œå»æ‰ä¸‹æ–¹æ§åˆ¶é¢æ¿æ¨¡å—çš„æ³¨é‡Šã€‚
# æœºåœºè®¢é˜…
proxy-providers:
  starlinkclash:
    url: "https://rssstarlink.ei38d3if3.xyz/s/b5cae56528e10b2009934bb8be10cc9f"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ğŸš€ é»˜è®¤ä»£ç†
  icy:
    url: "https://icy.xynet.ggff.net/icy/sub"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿  
  subsnip:
    url: "https://subsnip.xynet.ggff.net/xynet?sub"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿ 

# =========================
# èŠ‚ç‚¹
# =========================
proxies:
  - {name: ç›´è¿, type: direct}

# =========================
# å…¨å±€é…ç½®
# =========================
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: warning
# find-process-mode: off
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# =========================
# Sniffer
# =========================
sniffer:
  enable: true
  sniff:
    HTTP: {ports: [80, 8080-8085], override-destination: true}
    TLS: {ports: [443]}
  force-domain: ["+.v2ex.com"]
  skip-domain: ["+.baidu.com"]

# =========================
# TUN
# =========================
tun:
  enable: true
  stack: mixed
  dns-hijack: ["any:53"]
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false

# =========================
# DNS
# =========================
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/15
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "rule-set:telegram_domain"
    - "+.msftconnecttest.com"
  default-nameserver: [223.5.5.5]
  proxy-server-nameserver: [https://223.5.5.5/dns-query]
  nameserver: [223.5.5.5, 211.137.58.20]

# =========================
# Proxy Groupsï¼ˆTelegramå»æ‰é»˜è®¤ä»£ç†/ç›´è¿ï¼Œå¢åŠ èŠ‚ç‚¹çŠ¶æ€å¯è§†åŒ–ï¼‰
# =========================
proxy-groups:
  - {name: "ğŸš€ é»˜è®¤ä»£ç†", type: select, proxies: ["ğŸ”¯ é¦™æ¸¯æ•…è½¬","ğŸ”¯ æ—¥æœ¬æ•…è½¬","ğŸ”¯ ç‹®åŸæ•…è½¬","ğŸ”¯ ç¾å›½æ•…è½¬","â™»ï¸ è‡ªåŠ¨é€‰æ‹©","ğŸŒ å…¨éƒ¨èŠ‚ç‚¹"]}
  - {name: "ğŸ“¹ YouTube", type: fallback, include-all: true, filter: "^((?!(ç›´è¿)).)*$", url: "https://www.youtube.com/s/desktop/", interval: 600, tolerance: 80}
  - {name: "ğŸ¥ NETFLIX", type: fallback, include-all: true, filter: "^((?!(ç›´è¿)).)*$", url: "https://www.netflix.com/title/80018499", interval: 600, tolerance: 80}
  - {name: "ğŸ¤– ChatGPT", type: fallback, include-all: true, filter: "^((?!(ç›´è¿)).)*$", url: "https://chat.openai.com/cdn-cgi/trace", interval: 600, tolerance: 80}
  - {name: "ğŸ‘¨ğŸ¿â€ğŸ’» GitHub", type: fallback, include-all: true, filter: "^((?!(ç›´è¿)).)*$", url: "https://github.com", interval: 600, tolerance: 80}
  - {name: "ğŸ€ Google", type: fallback, include-all: true, filter: "^((?!(ç›´è¿)).)*$", url: "https://www.gstatic.com/generate_204", interval: 600, tolerance: 80}
  - {name: "ğŸ“² Telegram", type: fallback, include-all: true, filter: "^((?!(ç›´è¿)).)*$", url: "https://api.telegram.org", interval: 600, tolerance: 80}
  - {name: "ğŸš€ game", type: select, proxies: ["ğŸ”¯ é¦™æ¸¯æ•…è½¬","ğŸ”¯ æ—¥æœ¬æ•…è½¬","ğŸ”¯ ç‹®åŸæ•…è½¬","ğŸ”¯ ç¾å›½æ•…è½¬","â™»ï¸ è‡ªåŠ¨é€‰æ‹©","ğŸŒ å…¨éƒ¨èŠ‚ç‚¹"]}
  - {name: "ğŸ”¯ é¦™æ¸¯æ•…è½¬", type: fallback, include-all: true, filter: "(?i)(æ¸¯|hk)", interval: 600}
  - {name: "ğŸ”¯ æ—¥æœ¬æ•…è½¬", type: fallback, include-all: true, filter: "(?i)(æ—¥|jp)", interval: 600}
  - {name: "ğŸ”¯ ç‹®åŸæ•…è½¬", type: fallback, include-all: true, filter: "(?i)(æ–°|sg)", interval: 600}
  - {name: "ğŸ”¯ ç¾å›½æ•…è½¬", type: fallback, include-all: true, filter: "(?i)(ç¾|us)", interval: 600}
  - {name: "â™»ï¸ è‡ªåŠ¨é€‰æ‹©", type: url-test, include-all: true, url: "https://www.gstatic.com/generate_204", interval: 600}
  - {name: "ğŸŒ å…¨éƒ¨èŠ‚ç‚¹", type: select, include-all: true}

# =========================
# Rules
# =========================
rules:
  - RULE-SET,private_ip,ç›´è¿,no-resolve
  - RULE-SET,private_domain,ç›´è¿
  - RULE-SET,BanAD,REJECT
  - RULE-SET,BanProgramAD,REJECT
  - RULE-SET,self_game1,ğŸš€ game
  - RULE-SET,ai_openai,ğŸ¤– ChatGPT
  - RULE-SET,ai_copilot,ğŸ¤– ChatGPT
  - RULE-SET,ai_other,ğŸ¤– ChatGPT
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,telegram_ip,ğŸ“² Telegram,no-resolve
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ç›´è¿
  - RULE-SET,cn_ip,ç›´è¿
  - MATCH,ğŸš€ é»˜è®¤ä»£ç†

# =========================
# Rule Providers
# =========================
rule-providers:
  self_game1: {type: http, interval: 86400, behavior: domain, format: text, url: https://raw.githubusercontent.com/zihaoxy/openclash/refs/heads/main/game.list}
  
  private_domain: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs}
  private_ip: {type: http, interval: 86400, behavior: ipcidr, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs}
  BanAD: {type: http, interval: 86400, behavior: classical, format: text, url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list}
  BanProgramAD: {type: http, interval: 86400, behavior: classical, format: text, url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list}
  ai_openai: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.mrs}
  ai_copilot: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geo-site/github-copilot.mrs}
  ai_other: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs}
  github_domain: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs}
  youtube_domain: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs}
  netflix_domain: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs}
  google_domain: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs}
  telegram_domain: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs}
  telegram_ip: {type: http, interval: 86400, behavior: ipcidr, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs}
  geolocation-!cn: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs}
  cn_domain: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs}
  cn_ip: {type: http, interval: 86400, behavior: ipcidr, format: mrs, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs}
